name: Automatic Versioning

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm set "//npm.pkg.github.com/:_authToken" ${{secrets.NPM_PAT}}
      - run: npm ci
  version:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm set "//npm.pkg.github.com/:_authToken" ${{secrets.NPM_PAT}}
      - run: npm install -g @jmcmahon1999/convver --@jmcmahon1999:registry=https://npm.pkg.github.com/
      - name: Set Credentials
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Convver Update
        id: convver-update
        run: convver update npm -q
      - id: convver-current
        run: echo "tag='v$( convver current)'" >> $GITHUB_OUTPUT
      - name: Push Changes
        if: steps.convver-current.outcome == 'success'
        run: git push --follow-tags
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_PAT }}
          tag: ${{ steps.convver-update.outputs.tag }}
        run: |
          gh release create "${tag#v}" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${tag#v}" \
            --generate-notes
